name: Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.extract-java-version.outputs.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Extract Java Version
        id: extract-java-version
        run: |
          JAVA_VERSION=$(grep 'java-sdk' gradle/libs.versions.toml | awk -F= '{print $2}' | tr -d '"' | xargs)
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: 'zulu'
          java-version: ${{ needs.setup.outputs.java-version  }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3

  test:
    needs: [ setup, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: 'zulu'
          java-version: ${{ needs.setup.outputs.java-version }}

      - name: Setup Gradle and execute check task
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run Unit Tests
        run: ./gradlew test
